# Transposición de matrices

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
transposed_matrix = matrix.T
print(matrix)
print()
print(transposed_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Reshape
modifica el tamaño de la matrix

In [4]:
array = np.arange(1,13)
reshaped_array = array.reshape(3, 4)
print(array)
print()
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Invertir un array

In [5]:
reversed_array = array[::-1]
print(array)
print()
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[12 11 10  9  8  7  6  5  4  3  2  1]


### Flattenning
Consiste en convertir un array multidimensional en uno unidimensional

In [9]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
flattened_matrix = matrix.flatten()
print(matrix)
print()
print(flattened_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]
