# Calculo Matriciales

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

# suma
sum = A + B
print(A)
print(B)
print("Suma:\n", sum)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Suma:
 [[ 6  8]
 [10 12]]


In [3]:
#Multiplicación
produc = np.dot(A, B)
print("Multiplicación:\n", produc)

Multiplicación:
 [[19 22]
 [43 50]]


In [6]:
#Determinante
A = np.array([[1,2], [3,4]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(A)
print("Determinante de A:\n", det_A)
print("Inversa de A:\n", inv_A)

[[1 2]
 [3 4]]
Determinante de A:
 -2.0000000000000004
Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# Sistema de ecuaciones
resolver ax = b

In [7]:
b = np.array([9,11])
x = np.linalg.solve(A, b)
print("Solución del sistema Ax = b:\n", x)

Solución del sistema Ax = b:
 [-7.  8.]
