# Indexación y Slicing


In [3]:
import numpy as np

array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])

20
50


In [5]:
print(array[1:4])

[20 30 40]


In [6]:
print(array[1:7])

[20 30 40 50]


In [7]:
print(array[-1:-7])

[]


Indexación Booleana

In [10]:
array = np.array([10,20,30,40,50])
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [13]:
index = [2,0,4]
print(array[index])

[30 10 50]


In [16]:
array = np.random.randint(1, 10, size=(3,3))
print(array)
print(array[0,1])

[[6 5 3]
 [3 5 6]
 [4 1 8]]
5


In [17]:
print(array[:2, :2])

[[6 5]
 [3 5]]


# Ejercicios

1. Acceder a elementos específicos:
Crea un arreglo de 10 números y accede al cuarto y penúltimo elemento usando índices positivos y negativos.

In [19]:
arreglo = np.array([1,2,3,4,5,6,7,8,9,10])
print(arreglo[3:-1])

[4 5 6 7 8 9]


2. Slicing de arreglos:
Dado un arreglo de números del 1 al 20, extrae los elementos entre las posiciones 3 y 7, y luego los elementos de las últimas 5 posiciones.

In [25]:
arreglo = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arreglo[3:7])
print(arreglo[-5:])

[4 5 6 7]
[16 17 18 19 20]


3. Indexing con booleanos:
Crea un arreglo de números aleatorios entre 0 y 100. Usa una expresión booleana para acceder solo a los números mayores a 50.

In [31]:
arreglo = np.random.randint(1, 100, size=100)
bool_index = arreglo > 50
print(bool_index)

[False False False False False  True False False False  True False False
 False  True  True  True  True False False False  True  True False  True
  True  True  True  True  True False False  True  True False False  True
 False False  True  True  True False False  True  True False False  True
 False False  True False  True  True False False False False  True False
  True  True False  True  True False False False  True False  True False
 False False False  True  True False False False False  True False False
  True False  True False False False False False  True  True False  True
  True False False False]


4. Indexación con múltiples índices:
Dado un arreglo de 8 elementos, crea una lista de índices para acceder a los elementos en las posiciones 1, 4, y 6.

In [37]:
arreglo = np.array([10,20,30,40,50,60,70,80])
index = [1,4,6]
print(arreglo[index])

[20 50 70]


5. Matrices bidimensionales:
Genera una matriz 4x4 de números aleatorios entre 10 y 50, y accede a la submatriz de 2x2 ubicada en la esquina inferior derecha.

In [41]:
arreglo = np.random.randint(10, 50, size=(4, 4))
print(arreglo)
print()
print(arreglo[2:,2:])

[[37 33 35 22]
 [36 32 27 25]
 [11 27 38 32]
 [15 14 21 15]]

[[38 32]
 [21 15]]
