## BroadCasting

In [1]:
import numpy as np

In [2]:
prices = np.array([100, 200, 300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices )
# Output: [ 90. 180. 270.]

[ 90. 180. 270.]


In [3]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([10,20,30])
discount_prices  = prices + discount
print(prices)
print()
print(discount_prices )

[[403 156 350]
 [479 316 303]
 [118 390 230]]

[[413 176 380]
 [489 336 333]
 [128 410 260]]


Operaciones logicas

In [4]:
array = np.array([1,2,3,4,5])
print(np.all(array > 9))

False


In [5]:
print(np.any(array > 4))

True


Concatenar

In [6]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated_a = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_a)
print(concatenated_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


Stacking

In [7]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [8]:
stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[1 2 3 4 5 6]


Split

In [9]:
array_c = np.arange(1, 10)
split_array = np.split(array_c, 3)
print(array_c)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# Unique

In [10]:
survey_responses = np.array (["bueno", "excelente", "malo",
                              "bueno", "malo", "excelente",
                              "bueno", "bueno", "malo",
                              "excelente", "qa"])
print(np.unique(survey_responses))

['bueno' 'excelente' 'malo' 'qa']


In [11]:
unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)

['bueno' 'excelente' 'malo' 'qa']
[4 3 3 1]


Vistas

In [12]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)
array_x[1:3] = [10,11]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [13]:
array_x = np.arange(10)
copy_x = array_x[[1,2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10,11]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]
